# Configuration file for trinag model and hyperparameter settings
# of crop and weed dataset

#'0,1,2,3'
gpus_to_use: '3'
DPI: 300
LOG_WANDB: True
BENCHMARK: True

project_name: 'CycleGAN'
experiment_name: 'cyclegan_no_gs'


log_directory: "/home/user01/data/talha/cyclegan/logs/"
checkpoint_path: "/home/user01/data/talha/cyclegan/chkpts/"
GEN_A_CHKPT: "gen_a.pth.tar"
GEN_B_CHKPT: "gen_b.pth.tar"
DISC_A_CHKPT: "disc_a.pth.tar"
DISC_B_CHKPT: "disc_b.pth.tar"
# Data loader parameters

data_dir: "/home/user01/data/talha/cyclegan/data/horse2zebra/"
# add sub dirs inside of train/val and test
sub_directories: ['train/', 'test/']
Augment_data: True
Normalize_data: True
Shuffle_data: True

pin_memory: True
num_workers: 6

img_height: 256
img_width: 256

# 4 means output of network is 4 times downsampled than input.
input_channels: 3
batch_size: 1
WEIGHT_DECAY: 0.00005
# only for training data


LAMBDA_IDENTITY: 5.0
LAMBDA_CYCLE: 10.0

learning_rate: 0.0002
epochs: 200
start_epoch: 0
decay_epoch: 100